string player_name
string lobby_name
string lobby_id
uint64 desired_player_color # 0 - random, 1 - black, 2 - red
uint64 player_public_key
---
string lobby_name
string lobby_id
bool joined # If false, check error_msg
string black_player_name
string red_player_name
bool black_player_ready
bool red_player_ready
string error_msg
uint64 checksum_sig