string player_name
string lobby_name
string lobby_id
uint64 encrypted_hashed_lobby_password
uint64 checksum_sig
---
string lobby_name
string lobby_id
bool joined # If false, check error_code
string black_player_name
string red_player_name
bool black_player_ready
bool red_player_ready
uint64 timer_seconds
uint64 error_code
uint64 checksum_sig